language: python
python:
  - '2.7'
install:
  - pip install -q coveralls flake8
  - pip install -r requirements/docs.txt
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
  - python setup.py install
  - cd docs && make html
after_success:
  coveralls
